### ISSUE TITLE
오류 관련 질문

### ISSUE THREAD

**Issue by samsunghappytree123** [kijk2869/discodo#122]
python 3.8.5, 샘플코드로 실행해 보았습니다. (!join 명령어)
``discord.py 1.5.1, discodo 2.3.9``입니다.

```py
Ignoring exception in command join:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\Happytree Samsung\Discord File\Team HT\Shrimp\Cogs\music2.py", line 18, in _join
    await self.bot.ws.voice_state(ctx.guild.id, ctx.author.voice.channel.id)
AttributeError: 'NoneType' object has no attribute 'voice_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'voice_state'

**Comment by kijk2869** [comment]
코드를 따로 수정하지 않고 직접 실행한 것이 맞나요?

**Comment by samsunghappytree123** [comment]
[example](https://github.com/kijk2869/discodo/blob/master/example/local/example2.py)을 사용하였으나, ``@commands.Cog.listener()``를 제외한 모든 코드를 복사하여 실행했습니다.

**Comment by kijk2869** [comment]
![image](https://user-images.githubusercontent.com/35522821/104300964-72dc3480-550a-11eb-944a-2f0ea3b83c1a.png)

cogs 폴더가 보여서 말씀드렸던겁니다.

그럼 `await self.bot.ws.voice_state(ctx.guild.id, ctx.author.voice.channel.id)` 이 코드 앞에

`print((self.bot, self.bot.ws))`를 추가한 후 나오는 값을 캡쳐해주세요.

**Comment by samsunghappytree123** [comment]
``(<discord.ext.commands.bot.AutoShardedBot object at 0x045F8160>, None)`` self.bot.ws가 None으로 뜨는 거 같네요.

**Comment by kijk2869** [comment]
예제코드는 `AutoShardedBot`을 사용하지 않았습니다.

**Comment by samsunghappytree123** [comment]
``AutoShardedBot``을 지우면 되나요?

**Comment by kijk2869** [comment]
> `AutoShardedBot`을 지우면 되나요?

Bot으로 교체하시거나 코드를 수정해야합니다.

**Comment by samsunghappytree123** [comment]
AutoShardedBot을 지우니 잘 되긴 하네요. 혹시 추후에 지원하실 계획은 있으신가요?

**Comment by kijk2869** [comment]
> AutoShardedBot을 지우니 잘 되긴 하네요. 혹시 추후에 지원하실 계획은 있으신가요?

디스코도 문제가 아닙니다.

**Comment by samsunghappytree123** [comment]
알겠습니당
