### ISSUE TITLE
VoiceClient still exist in removed guild

### ISSUE THREAD

**Issue by simsimler** [kijk2869/discodo#214]
When the bot removed from the guild, the VoiceClient isn't destroyed. But it still exist and trying to send something to that channel.
And I can see an error.
```
future: <Task finished name='Task-1565279' coro=<DPYClient._onAnyNodeEvent() done, defined at /usr/local/lib/python3.8/site-packages/discodo/client/DPYClient.py:171> exception=TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")>,
future: <Task finished name='Task-1565358' coro=<DPYClient._onAnyNodeEvent() done, defined at /usr/local/lib/python3.8/site-packages/discodo/client/DPYClient.py:171> exception=TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")>,
future: <Task finished name='Task-1565441' coro=<DPYClient._onAnyNodeEvent() done, defined at /usr/local/lib/python3.8/site-packages/discodo/client/DPYClient.py:171> exception=TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")>,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/discodo/client/DPYClient.py", line 176, in _onAnyNodeEvent,
    vc = self.getVC(guild, safe=True),
  File "/usr/local/lib/python3.8/site-packages/discodo/client/DPYClient.py", line 232, in getVC,
    if int(guild) not in self.voiceClients and not safe:,
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
Reproduce: Kick the bot when it playing something on guild's voice channel

**Comment by kijk2869** [comment]
Sorry for late response.
I'm so busy that I can't afford to do this.
If you can, please make some pr
