### ISSUE TITLE
"RuntimeError: can't start new thread"

### ISSUE THREAD

**Issue by simsimler** [kijk2869/discodo#216]
```
Exception in callback VoiceClient.handleGetState({'guild_id': '653083797763522580', 'traceback': {'RuntimeError': "can't start new thread"}})(),
handle: <Handle VoiceClient.handleGetState({'guild_id': '653083797763522580', 'traceback': {'RuntimeError': "can't start new thread"}})()>,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run,
    self._context.run(self._callback, *self._args),
  File "/usr/local/lib/python3.8/site-packages/discodo/client/voice_client.py", line 147, in handleGetState,
    options = data["options"],
KeyError: 'options'
```
https://github.com/kijk2869/discodo/blob/master/discodo/source/PyAVSource.py in line 140
Error when starting new thread.
Reproduce: Just make a lots of threads

**Comment by kijk2869** [comment]
Sorry for late response.
This may be some critical bug and require many works.
However, I'm so busy that I can't afford to do this now.
I'll work on it when I have time.
If possible before that, please open pr.
