### ISSUE TITLE
"AttributeError: module 'websockets' has no attribute 'client'" when import discodo

### ISSUE THREAD

**Issue by simsimler** [kijk2869/discodo#219]
# What is Problem?
`AttributeError: module 'websockets' has no attribute 'client'` when import discodo
## Full Error
```
Traceback (most recent call last):
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\main.py", line 7, in <module>
    from models import Chorok, ChorokContext
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\models.py", line 8, in <module>
    import discodo
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\venv\lib\site-packages\discodo\__init__.py", line 7, in <module>
    from .client import *
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\venv\lib\site-packages\discodo\client\__init__.py", line 2, in <module>
    from .node import Node, Nodes
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\venv\lib\site-packages\discodo\client\node.py", line 14, in <module>
    from .gateway import NodeConnection
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\venv\lib\site-packages\discodo\client\gateway.py", line 16, in <module>
    class NodeConnection(websockets.client.WebSocketClientProtocol):
  File "C:\Users\simsimler\Coding\Discord_Bot\Chorok\venv\lib\site-packages\websockets\imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
```
# How to fix it?
Just downgrade websockets module to 8.1

**Comment by kijk2869** [comment]
This library uses websockets 8.1

https://github.com/kijk2869/discodo/blob/5543af5e670fecf139994328ca508c294b2c1010/requirements.txt#L3

please make sure the deps version
