### ISSUE TITLE
AttributeError: 'ShardInfo' object has no attribute 'ws'

### ISSUE THREAD

**Issue by decave27** [kijk2869/discodo#221]
Error Message:
```
Ignoring exception in command join:
Traceback (most recent call last):
  File "/home/decave27/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/decave27/dev/discodo-test/cogs/music.py", line 99, in join
    VC = await self.audio.connect(ctx.author.voice.channel)
  File "/home/decave27/.local/lib/python3.8/site-packages/discodo/client/DPYClient.py", line 291, in connect
    await self.getWebsocket(channel.guild.shard_id).voice_state(
  File "/home/decave27/.local/lib/python3.8/site-packages/discodo/client/DPYClient.py", line 245, in getWebsocket
    return self.client.shards[id].ws
AttributeError: 'ShardInfo' object has no attribute 'ws'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/decave27/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/decave27/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/decave27/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ShardInfo' object has no attribute 'ws'
```

Using discord.ext.commands.AutoShardedBot when setting discodo.DPYClien doesn't seem to work.
(If I use discord.ext.commands.Bot instead, it works.)

Is there any way to solve this?

**Comment by kijk2869** [comment]
Sorry for late response.
The structure of discord.py seems to have changed.
However, I'm so busy that I can't afford to do this.
If you can, please make some pr
