### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by Yoruroong** [kijk2869/discodo#45]
```
[2020-09-16 09:04:47,097] [event.py] [discodo.event:event] [INFO]: Voice Client of 621870504147681311 not found. create new one.
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<DiscordEvent.parseVoiceServerUpdate() done, defined at /usr/local/lib/python3.8/dist-packages/discodo/event.py:53> exception=ValueError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discodo/event.py", line 63, in parseVoiceServerUpdate
    vc = VoiceClient(self.client, data)
  File "/usr/local/lib/python3.8/dist-packages/discodo/voice_client.py", line 18, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discodo/voice_connector.py", line 42, in __init__
    self.encoder = opus.Encoder()
  File "/usr/local/lib/python3.8/dist-packages/discodo/natives/opus.py", line 150, in __init__
    raise ValueError
ValueError
[2020-09-16 09:04:47,350] [voice_client.py] [discodo.VoiceClient:voice_client] [INFO]: destroying voice client of 621870504147681311.
Exception ignored in: <function VoiceClient.__del__ at 0x7ff83802a0d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discodo/voice_client.py", line 90, in __del__
    if self.player and self.player.is_alive():
AttributeError: 'VoiceClient' object has no attribute 'player'
```
파이썬 3.8.2, 샘플코드로 `!join`을 실행할 때 디스코도 서버에서 오류가 발생함

**Comment by sannoob** [comment]
> Opus 라이브러리를 찾을 수 없습니다.
> 
> 환경이 리눅스라면 `libopus-dev`를 설치해주세요.
> 
> 관련 메시지는 리라이트때 수정하겠습니다.

감사합니다

**Comment by kijk2869** [comment]
왜 니가 감사하세요 콜라보레이터님

**Comment by sannoob** [comment]
저도 저 오류가 뭔지 몰랐어요

**Comment by Yoruroong** [comment]
해결됐어요, 감사합니다 :D
