### ISSUE TITLE
༼ つ ◕_◕ ༽つ

### ISSUE THREAD

**Issue by Yoruroong** [kijk2869/discodo#98]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\yoru\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "test.py", line 65, in on_message
    Source = await vc.loadSource(message.content[5:].strip())
  File "C:\Users\yoru\AppData\Local\Programs\Python\Python37\lib\site-packages\discodo\client\voice_client.py", line 70, in loadSource
    return (await self.query("loadSource", {"query": Query}))["source"]
KeyError: 'source'
```

await self.query("loadSource", {"query": Query})
```
{'traceback': {'JSONDecodeError': 'Extra data: line 1 column 258633 (char 258632)'}, 'guild_id': 621870504147681311}
```

server(ubuntu 20.04)
```
[2020-12-12 08:33:43,024] [websocket.py] [discodo.server:websocket] [INFO]: new websocket connection created from 
[2020-12-12 08:33:44,456] [event.py] [discodo.event:event] [INFO]: recieve self voice update. set session id 9544877c55b74a23ac04b5faa78f065e
[2020-12-12 08:33:44,459] [event.py] [discodo.event:event] [INFO]: Voice Client of 621870504147681311 not found. create new one.
[2020-12-12 08:33:44,646] [event.py] [discodo.event:event] [INFO]: Voice server update recieved. connect to new endpoint
[2020-12-12 08:33:44,646] [voice_connector.py] [discodo.VoiceConnector:voice_connector] [INFO]: voice endpoint south-korea367.discord.media detected.
[2020-12-12 08:33:44,709] [gateway.py] [discodo.gateway:gateway] [INFO]: select encrypt mode xsalsa20_poly1305_suffix
[2020-12-12 08:33:44,721] [gateway.py] [discodo.gateway:gateway] [INFO]: recieved voice secret key.
[2020-12-12 08:33:47,292] [search.py] [discodo.extractor.youtube:search] [INFO]: Downloading search page of how far ill go
[2020-12-12 08:33:48,150] [search.py] [discodo.extractor.youtube:search] [INFO]: Downloading search page of how far ill go
```

**Comment by kijk2869** [comment]
More information needed.

What is your discodo version?

It seems to me that it was fixed in `https://github.com/kijk2869/discodo/commit/af6ba0bb29297d23800ca2ec14c33ffd042df371`

**Comment by kijk2869** [comment]
I noticed that there is not any release.
